### PR TITLE
stop apps when the device is starting

### PR DESCRIPTION
**Pull request by alvajardila**

### CODE REVIEW

**Comment by eighteyes** [comment]
@alvajardila please address comments, and i'll merge in this sprint

**Comment by eighteyes** [comment]
I have an app that is 
screen shot 2016-11-07 at 1 47 02 pm

This error should be cleared with this, and the app should be set to inactive.

**Comment by alvajardila** [comment]
This PR is necessary for the correct operation of this:

https://github.com/matrix-io/matrix-cli/pull/42

**Comment by eighteyes** [comment]
Getting this error when starting the device `123456` on demo.admobilize@gmail.com (dev)

```
UNKNOWN ERROR! Error: Callback was already called.
    at /home/pi/matrix-os/node_modules/matrix-firebase/node_modules/async/dist/async.js:985:32
    at /home/pi/matrix-os/index.js:309:13
    at /home/pi/matrix-os/node_modules/matrix-firebase/lib/app.js:250:9
    at /home/pi/matrix-os/node_modules/matrix-firebase/node_modules/firebase/database-node.js:162:614
    at rb (/home/pi/matrix-os/node_modules/matrix-firebase/node_modules/firebase/database-node.js:61:165)
    at Ob (/home/pi/matrix-os/node_modules/matrix-firebase/node_modules/firebase/database-node.js:49:215)
    at Pb (/home/pi/matrix-os/node_modules/matrix-firebase/node_modules/firebase/database-node.js:48:701)
    at Ue.h.Hb (/home/pi/matrix-os/node_modules/matrix-firebase/node_modules/firebase/database-node.js:231:440)
    at U.h.set (/home/pi/matrix-os/node_modules/matrix-firebase/node_modules/firebase/database-node.js:247:320)
    at Object.setStatus (/home/pi/matrix-os/node_modules/matrix-firebase/lib/app.js:263:6)
```

**Comment by alvajardila** [comment]
On that line is called the method getStatus of app in te old version of the matrix firebase that method is `on` instead `once`.
`    function stopAllApps(cb){
      debug('Stop all apps...'.green);
      //Retrieve status for each app
      async.forEach(Object.keys(Matrix.localApps), function (appId, done) {
        Matrix.service.firebase.app.getStatus(appId, function (status) {
           //Set default status to inactive
          if (_.isUndefined(status)) status = "inactive";
          //If the status is active set online false and status inactive on the app
          if(status === "active"){
            Matrix.service.firebase.app.setOnline(appId, false);
            Matrix.service.firebase.app.setStatus(appId, 'inactive');
          }else{
            done();
          }
        });
      }, function(err) {
        cb();
      });
    }
`
Please remove the matrix firebase dependence and reinstall.

**Comment by eighteyes** [comment]
Great! Works!

**Pull request merged**
