### PR TITLE
Fix wrong temperature readings, average from 2 sensors

### PR DESCRIPTION
**Pull request by vjoao**
I noticed temperature readings for the matrix-os were wrong when I tried to use them for the hackathon.
Tried reading the Humidity sensor with the HAL and with MALOS and both returned the *correct* value.
Just edited the matrix-os files to check whether the temperature from Pressure sensor was OK and it was just fine (about 35C). Then, I realized in protobuf definition file for temperature you have the 'temperature_raw' variable which surprisingly or not returns the correct value for the temperature sensor.

I corrected that and did a bit more: evaluated the temperature as being the average between both sensors that inform temperature data: Humidity and Pressure.

### CODE REVIEW

**Comment by vjoao** [comment]
Is travis configured correctly?

**Comment by vjoao** [comment]
Sorry bout closing it, miss click =x

**Comment by brianofrokk3r** [comment]
@vjoao we will discuss internally before we merge any PR regarding this change.

**Comment by vjoao** [comment]
@brianofrokk3r no problem =)

Correct if I am mistaken, but the is `temperature` key in the humidity sensor your try to calibrate regarding the board temperature?

**Comment by eighteyes** [comment]
@vjoao yes, travis is configured correctly. it doesn't send the login secret to your PR, i guess that makes sense. i moved the PR to be vs  `dev` branch. we're going to discuss the temp issue today. hold tight.

**Comment by eighteyes** [comment]
@vjoao Ok, been reviewing, and this is not the right way to solve this issue. Thank you for your submission.

**Comment by di3goleite** [comment]
What should be the right way @eighteyes ? Do you have a short answer?

**Comment by eighteyes** [comment]
No short answer, this needs to be resolved outside of mos.

**Comment by vjoao** [comment]
HAL and MALOS return around 35C for temperature. MOS returns -0.78 on `temperature` and around 35 on `temperature_raw`... I don't understand. Would be good if you could try explaining it a little bit more, just because I'm curious about this issue. Thanks for your time =)

**Pull request closed without merging**
