### PR TITLE
Enable gesture and face 

### PR DESCRIPTION
**Pull request by eighteyes**
See documentation for usage 

https://matrix-io.github.io/matrix-documentation/API/computer-vision/
https://matrix-io.github.io/matrix-documentation/Configuration/services/

Test apps
https://github.com/matrix-io/matrix-srcjs-apps.git

### CODE REVIEW

**Comment by brianofrokk3r** [comment]
@eighteyes when running face example in `matrix-src-apps` I get a crash.
```
 device.service start> +5ms { type: 'service-init', name: 'face', options: {} }
Uncaught exception:  TypeError: Cannot read property 'name' of undefined
    at Object.registerComponent (/home/pi/matrix-os/lib/service/zeromq.js:32:45)
    at EventEmitter.start (/home/pi/matrix-os/lib/device/service.js:91:37)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at ChildProcess.messageHandler (/home/pi/matrix-os/lib/event/app.js:108:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) TypeError: Cannot read property 'name' of undefined
    at Object.registerComponent (/home/pi/matrix-os/lib/service/zeromq.js:32:45)
    at EventEmitter.start (/home/pi/matrix-os/lib/device/service.js:91:37)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at ChildProcess.messageHandler (/home/pi/matrix-os/lib/event/app.js:108:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
UNKNOWN ERROR! TypeError: Cannot read property 'name' of undefined
    at Object.registerComponent (/home/pi/matrix-os/lib/service/zeromq.js:32:45)
    at EventEmitter.start (/home/pi/matrix-os/lib/device/service.js:91:37)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at ChildProcess.messageHandler (/home/pi/matrix-os/lib/event/app.js:108:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  matrix DESTROYING +13ms
```

**Comment by eighteyes** [comment]
thanks for that @brianofrokk3r opened issue #31

**Comment by eighteyes** [comment]
woot no conflicts!

**Comment by eighteyes** [comment]
@brianofrokk3r @diegoribero I'd like to merge this beast, please test?

**Comment by diegoribero** [comment]
Tested deploy, install, uninstall, start, stop and both apps worked for me

**Comment by diegoribero** [comment]
@eighteyes think we shouldn't include `apps/clock2` and `apps/gestureTest`, otherwise looks good

**Comment by brianofrokk3r** [comment]
Remove the `apps` from the repo.

**Comment by eighteyes** [comment]
good catch @diegoribero that will be addressed

**Pull request merged**
