### PR TITLE
Uninstall flow fixed

### PR DESCRIPTION
**Pull request by diegoribero**
Uninstall was broken, now it actually uninstalls and it doesn't install other apps...

Requires **matrix-firebase** `dr/appInstallUpdate` update

### CODE REVIEW

**Comment by brianofrokk3r** [comment]
@diegoribero any CLI dependencies?

**Comment by eighteyes** [comment]
I do believe this requires an npm install on mos

**Comment by eighteyes** [comment]
It is important that uninstall does not install other apps.

Good work!

**Comment by brianofrokk3r** [comment]
@diegoribero @eighteyes can we delete this branch?

**Comment by diegoribero** [comment]
Yeah, deleting

**Pull request merged**
