### PR TITLE
Jt/firebase network

### PR DESCRIPTION
**Pull request by jmtovarf**
Get device network (Ethernet or Wireless) and set this information on firebase `device/public/runtime/netinfo`.

Use branch `jt/update_network` on `matrix-firebase` module in order to test.

### CODE REVIEW

**Comment by brianofrokk3r** [comment]
@diegoribero @eighteyes why is this not passing? Do we need to rebase?

**Comment by eighteyes** [comment]
Getting this error
```
Uncaught exception:  { Error: Uncaught, unspecified "error" event. (Error getting wireless devices information)
    at Network.emit (events.js:163:17)
    at /Users/god/admob/matrix-os/lib/device/network.js:157:18
    at /Users/god/admob/matrix-os/node_modules/wireless-tools/wpa_cli.js:151:13
```

**Comment by brianofrokk3r** [comment]
What's the issue here?

**Comment by eighteyes** [comment]
@brianofrokk3r no issue now, it was erroring out for me locally.

**Pull request merged**
